---
booktitle: 'Proceedings of The TerraBytes {ICML} Workshop: Towards global datasets
  and models for Earth Observation'
shortname: TerraBytes
year: '2025'
volume: '292'
start: &1 2025-07-19
end: 2025-07-19
published: 2025-12-02
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: TerraBytes2025
month: 0
cycles: false
bibtex_editor: Audebert, Nicolas and Azizpour, Hossein and Barri\`{e}re, Valentin
  and Castillo Navarro, Javiera and Czerkawski, Mikolaj and Fang, Heng and Francis,
  Alistair and Marsocci, Valerio and Nascetti, Andrea and Yadav, Ritu
editor:
- given: Nicolas
  family: Audebert
- given: Hossein
  family: Azizpour
- given: Valentin
  family: Barrière
- given: Javiera
  family: Castillo Navarro
- given: Mikolaj
  family: Czerkawski
- given: Heng
  family: Fang
- given: Alistair
  family: Francis
- given: Valerio
  family: Marsocci
- given: Andrea
  family: Nascetti
- given: Ritu
  family: Yadav
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The TerraBytes {ICML} Workshop: Towards global datasets and models for Earth Observation
    Held in Vancouver, BC, Canada on 19 July 2025

  Published as Volume 292 by the Proceedings of Machine Learning Research on 02 December 2025.

  Volume Edited by:
    Nicolas Audebert
    Hossein Azizpour
    Valentin Barrière
    Javiera Castillo Navarro
    Mikolaj Czerkawski
    Heng Fang
    Alistair Francis
    Valerio Marsocci
    Andrea Nascetti
    Ritu Yadav

  Series Editors:
    Neil D. Lawrence
date_str: 19 Jul
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v292"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v292
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v292
email: ''
conference:
  name: TerraBytes - Towards global datasets and models for Earth Observation
  url: https://terrabytes-workshop.github.io/
  location: Vancouver, BC, Canada
  dates:
  - *1
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: terrabytes_cleaned_clean.bib
# Site settings
# Original source:  terrabytes_cleaned_clean.bib
